[pytest]
filterwarnings =
    ignore:The copy keyword is deprecated and will be removed in a future version.*:Warning
    ignore:divide by zero encountered in scalar divide:RuntimeWarning
    ignore:invalid value encountered in scalar divide:RuntimeWarning
    ignore:Co-variance matrix is underdetermined\. Inference will be invalid!:UserWarning
