#!/usr/bin/env python3
"""Generate a technical architecture document from code docstrings/comments.

The generator scans Python modules, extracts:
1) module docstrings
2) class and function docstrings
3) leading comment blocks immediately above top-level classes/functions

Output is a single markdown document suitable for architecture review.
"""

from __future__ import annotations

import argparse
import ast
import inspect
import sys
from dataclasses import dataclass
from pathlib import Path

DEFAULT_OUTPUT = Path("docs/TECHNICAL_ARCHITECTURE.md")
DEFAULT_SOURCE_DIRS = [Path("stack"), Path("pipelines"), Path("models")]


@dataclass(frozen=True)
class SymbolDoc:
    kind: str
    name: str
    line: int
    docstring: str
    leading_comments: list[str]


@dataclass(frozen=True)
class ModuleDoc:
    path: Path
    module_docstring: str
    module_header_comments: list[str]
    symbols: list[SymbolDoc]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a single architecture markdown document from code comments/docstrings."
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Output markdown file path.",
    )
    parser.add_argument(
        "--source-dir",
        action="append",
        default=[],
        help="Source directory to scan (can be provided multiple times).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write output; fail if generated content differs from existing file.",
    )
    return parser.parse_args()


def discover_python_files(source_dirs: list[Path]) -> list[Path]:
    paths: list[Path] = []
    for source_dir in source_dirs:
        if not source_dir.exists():
            continue
        paths.extend(sorted(source_dir.rglob("*.py")))
    return sorted(set(paths))


def extract_module_doc(path: Path) -> ModuleDoc:
    source = path.read_text(encoding="utf-8")
    source_lines = source.splitlines()
    tree = ast.parse(source, filename=str(path))

    module_docstring = _extract_module_docstring(tree)
    header_comments = _extract_header_comment_block(source_lines)

    symbols: list[SymbolDoc] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            symbols.append(
                SymbolDoc(
                    kind="class" if isinstance(node, ast.ClassDef) else "function",
                    name=node.name,
                    line=node.lineno,
                    docstring=ast.get_docstring(node) or "",
                    leading_comments=_extract_leading_comments(source_lines, node.lineno),
                )
            )

    return ModuleDoc(
        path=path,
        module_docstring=module_docstring,
        module_header_comments=header_comments,
        symbols=symbols,
    )


def _extract_header_comment_block(lines: list[str]) -> list[str]:
    comments: list[str] = []
    seen_code = False
    for line in lines:
        stripped = line.strip()
        if not stripped:
            if seen_code:
                break
            continue
        if stripped.startswith("#"):
            comments.append(stripped.lstrip("# ").rstrip())
            seen_code = True
            continue
        break
    return comments


def _extract_module_docstring(tree: ast.Module) -> str:
    """Extract module docstring, allowing docstring after __future__ imports."""
    primary = ast.get_docstring(tree)
    if primary:
        return primary

    for node in tree.body:
        if (
            isinstance(node, ast.ImportFrom)
            and node.module == "__future__"
        ):
            continue

        if (
            isinstance(node, ast.Expr)
            and isinstance(node.value, ast.Constant)
            and isinstance(node.value.value, str)
        ):
            return inspect.cleandoc(node.value.value)
        break

    return ""


def _extract_leading_comments(lines: list[str], lineno: int) -> list[str]:
    idx = lineno - 2
    block_rev: list[str] = []
    while idx >= 0:
        stripped = lines[idx].strip()
        if not stripped:
            if block_rev:
                break
            idx -= 1
            continue
        if stripped.startswith("#"):
            block_rev.append(stripped.lstrip("# ").rstrip())
            idx -= 1
            continue
        break
    return list(reversed(block_rev))


def build_markdown(modules: list[ModuleDoc], source_dirs: list[Path]) -> str:
    lines: list[str] = []
    lines.append("# Technical Architecture (Auto-Generated)")
    lines.append("")
    lines.append(
        "This document is generated from Python module docstrings and comment blocks."
    )
    lines.append("Generated by: `docs/generate_tech_docs.py`")
    lines.append("")
    lines.append("## Scanned Sources")
    lines.append("")
    for source_dir in source_dirs:
        lines.append(f"- `{source_dir}`")
    lines.append("")
    lines.append("## Module Inventory")
    lines.append("")
    lines.append("| Module | Summary |")
    lines.append("| --- | --- |")
    for module in modules:
        summary = _first_line(module.module_docstring) or "No module docstring."
        lines.append(f"| `{module.path.as_posix()}` | {summary} |")
    lines.append("")
    lines.append("## Detailed Architecture Notes")
    lines.append("")

    for module in modules:
        lines.append(f"### `{module.path.as_posix()}`")
        lines.append("")

        if module.module_docstring:
            lines.append(module.module_docstring.strip())
            lines.append("")
        else:
            lines.append("_No module docstring found._")
            lines.append("")

        if module.module_header_comments:
            lines.append("Header comments:")
            for comment in module.module_header_comments:
                lines.append(f"- {comment}")
            lines.append("")

        if not module.symbols:
            lines.append("_No top-level classes/functions found._")
            lines.append("")
            continue

        lines.append("Top-level symbols:")
        lines.append("")
        for symbol in module.symbols:
            symbol_doc = symbol.docstring.strip() or "No docstring."
            lines.append(
                f"- `{symbol.kind} {symbol.name}` (line {symbol.line}): { _first_line(symbol_doc) }"
            )
            if symbol.leading_comments:
                lines.append("  - Leading comments:")
                for comment in symbol.leading_comments:
                    lines.append(f"    - {comment}")
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def _first_line(text: str) -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def main() -> int:
    args = parse_args()
    source_dirs = [Path(p) for p in (args.source_dir or [])]
    if not source_dirs:
        source_dirs = DEFAULT_SOURCE_DIRS

    files = discover_python_files(source_dirs)
    modules = [extract_module_doc(path) for path in files]
    content = build_markdown(modules=modules, source_dirs=source_dirs)

    output_path = Path(args.output)
    if args.check:
        existing = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        if existing != content:
            print(f"Outdated generated doc: {output_path}")
            return 1
        print(f"Generated document is up to date: {output_path}")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Wrote technical architecture document: {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
